[package]
name = "mvtinfo"
version = "0.1.4"
authors = ["wsw0108 <wsw0108@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
reqwest = "0.9.12"
protobuf = { version = "2.4.0", features = ["with-bytes"] }
libflate = "0.1.25"

[build-dependencies]
protoc-rust = "2.4.0"
